# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 791, 571))
        self.stackedWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(self.page)
        self.label.setGeometry(QtCore.QRect(10, -20, 791, 591))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("1.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.page)
        self.pushButton.setGeometry(QtCore.QRect(630, 480, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setGeometry(QtCore.QRect(4, -5, 791, 541))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("2.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 490, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textEdit = QtWidgets.QTextEdit(self.page_3)
        self.textEdit.setGeometry(QtCore.QRect(140, 120, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_2.setGeometry(QtCore.QRect(130, 210, 581, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_3.setGeometry(QtCore.QRect(350, 310, 361, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.page_3)
        self.textEdit_4.setGeometry(QtCore.QRect(300, 410, 411, 41))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(10)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_3)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 490, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 791, 541))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("3.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(self.page_2)
        self.comboBox.setGeometry(QtCore.QRect(200, 130, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 190, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_3.setGeometry(QtCore.QRect(230, 260, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_4.setGeometry(QtCore.QRect(220, 320, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_4.setFont(font)
        self.comboBox_4.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_5 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_5.setGeometry(QtCore.QRect(210, 390, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_5.setFont(font)
        self.comboBox_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_6 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_6.setGeometry(QtCore.QRect(220, 450, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_6.setFont(font)
        self.comboBox_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_7 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_7.setGeometry(QtCore.QRect(600, 130, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_7.setFont(font)
        self.comboBox_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_8 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_8.setGeometry(QtCore.QRect(610, 200, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_8.setFont(font)
        self.comboBox_8.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_9 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_9.setGeometry(QtCore.QRect(600, 260, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_9.setFont(font)
        self.comboBox_9.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_10 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_10.setGeometry(QtCore.QRect(590, 320, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_10.setFont(font)
        self.comboBox_10.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_11 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_11.setGeometry(QtCore.QRect(600, 390, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_11.setFont(font)
        self.comboBox_11.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_12 = QtWidgets.QComboBox(self.page_2)
        self.comboBox_12.setGeometry(QtCore.QRect(620, 450, 51, 22))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.comboBox_12.setFont(font)
        self.comboBox_12.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_3.setGeometry(QtCore.QRect(640, 500, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_5.setGeometry(QtCore.QRect(540, 500, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_4 = QtWidgets.QLabel(self.page_4)
        self.label_4.setGeometry(QtCore.QRect(4, -5, 791, 541))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("4.jpg"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_4)
        self.label_5.setGeometry(QtCore.QRect(120, 90, 501, 30))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_4)
        self.label_6.setGeometry(QtCore.QRect(80, 160, 800, 40))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.page_4)
        self.label_7.setGeometry(QtCore.QRect(300, 190, 371, 250))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.page_4)
        self.label_8.setGeometry(QtCore.QRect(80, 220, 200, 222))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.stackedWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.go1)
        self.pushButton_2.clicked.connect(self.go2)
        self.pushButton_3.clicked.connect(self.go3)
        self.pushButton_4.clicked.connect(self.displayinfo)
        self.pushButton_5.clicked.connect(self.analyze)
        

    def go1(self):
        self.stackedWidget.setCurrentIndex(1)
    def go2(self):
        self.stackedWidget.setCurrentIndex(2)
    def go3(self):
        self.stackedWidget.setCurrentIndex(3)
        
#displayinfo
    def displayinfo(self):
        name = self.textEdit.toPlainText()

        self.label_5.setText("Hi! "+str(name))

#       dic archieve skill and quality(1-10) of skills
#       list archieve quality of skills
    def analyze(self):
        dic = {}
        lst = []
        lst_bestattribute=[]
        lst_goodattribute=[]

        
        pace = self.comboBox.currentText()
        pace = int(pace)
        dic["pace"] = pace
        lst.append(pace)

        
        finishing = self.comboBox_2.currentText()
        finishing = int(finishing)
        dic["finishing"] = finishing
        lst.append(finishing)

        
        dribbling = self.comboBox_3.currentText()
        dribbling = int(dribbling)
        dic["dribbling"] = dribbling
        lst.append(dribbling)


        passing = self.comboBox_4.currentText()
        passing = int(passing)
        dic["passing"] = passing
        lst.append(passing)

    
        vision = self.comboBox_5.currentText()
        vision = int(vision)
        dic["vision"] = vision
        lst.append(vision)

    
        tackling = self.comboBox_6.currentText()
        tackling = int(tackling)
        dic["tackling"] = tackling
        lst.append(tackling)

        
        strength = self.comboBox_7.currentText()
        strength = int(strength)
        dic["strength"] = strength
        lst.append(strength)

        
        teamwork = self.comboBox_8.currentText()
        teamwork = int(teamwork)
        dic["teamwork"] = teamwork
        lst.append(teamwork)

       
        stamina = self.comboBox_9.currentText()
        stamina = int(stamina)
        dic["stamina"] = stamina
        lst.append(stamina)

        
        marking = self.comboBox_10.currentText()
        marking = int(marking)
        dic["marking"] = marking
        lst.append(marking)

        
        handling = self.comboBox_11.currentText()
        handling = int(handling)
        dic["handling"] = handling
        lst.append(handling)

    
        positioning = self.comboBox_12.currentText()
        positioning = int(positioning)
        dic["positioning"] = positioning
        lst.append(positioning)
        lst2=lst.copy()
        s1=set(lst2)
        s1.remove(max(lst))
##        print (dic)
##        print(lst)
##        print(s1)

        for key,value in dic.items():
            if value == max(lst):
                lst_bestattribute.append(key)

        for key,value in dic.items():
            if value == max(s1):
                lst_goodattribute.append(key)

##        print(lst_bestattribute)
##        print(lst_goodattribute)

        #if 'passing' in lst_bestattribute or 'passing' in lst_bestattribute and 'vision' in lst_goodattribute:
        print("1test")
        cal = {}
        Striker = int(dic["pace"] + dic["finishing"])
        cal["Striker"] = Striker
        #print("1test1")
        Winger = int(dic["pace"] + dic["dribbling"])
        cal["Winger"] = Winger
        #print("1test2")
        Central_Attack_Midfield = int(dic["passing"] + dic["vision"])
        cal["Central Attack Midfield"] = Central_Attack_Midfield
        #print("1test3")
        Central_Midfield_Attack = int(dic["passing"] + dic["teamwork"])
        cal["Central Midfield(attack)"] = Central_Midfield_Attack
        #print("1test4")
        Central_Midflield_Defend = int(dic["tackling"] + dic["strength"])
        cal["Central Midfield(defend)"] = Central_Midflield_Defend
        #print("1test5")
        Full_Back = int(dic["stamina"] + dic["tackling"])
        cal["Full-Back"] = Full_Back
        #print("1test6")
        Center_Back =  int(dic["strength"] + dic["marking"])
        cal["CenterBack"] = Center_Back
        #print("1test7")
        Goalkeeper = int(dic["handling"] + dic["positioning"])
        cal["Goalkeeper"] = Goalkeeper
        #print("test")
##        cal["Striker"] = Striker
##        cal["Winger"] = Winger
##        cal["Central Attack Midfield"] = Central_Attack_Midfield
##        cal["Central Midfield(attack)"] = Central_Midfield_Attack
##        cal["Central Midflield(defend)"] = Central_Midfliel_Defend
##        cal["Full-Back"] = Full-Back
##        cal["CenterBack"] = Center-Back
##        cal["Goalkeeper"] = Goalkeeper

##       problem is it prints only gk.
        print(cal)

        print("test1")
        max_value = cal["Striker"]
        for k,v in cal.items():
            print("test2")
            if v > max_value:
                max_value = v
            if v == max_value: 
                self.label_6.setText("You are suitable at "+str(k))
                print("test3")

                if k == "Striker":
                    self.label_7.setText("The Striker position requires"+"\n-Pace"+"\n-Shooting")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/st.jpg"))
                elif k == "Winger":
                    self.label_7.setText("The Winger position requires"+"\n-Pace"+"\n-Dribbling")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/w1.jpg"))
                elif k == "Central Attack Midfield":
                    self.label_7.setText("The CAM position requires"+"\n-Passing"+"\n-Vision")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/cam.jpg"))
                elif k == "Central Midfield(attack)":
                    self.label_7.setText("The CM (attack) position requires"+"\n-Passing"+"\n-Teamwork")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/cm1.jpg"))
                elif k == "Central Midfield(defend)":
                    self.label_7.setText("The CM (defend) position requires"+"\n-Tackling"+"\n-Strength")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/cdm.jpg"))
                elif k == "Full-Back":
                    self.label_7.setText("The Full-Back position requires"+"\n-Tackling"+"\n-Stamina")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/fullback.jpg"))
                elif k == "CenterBack":
                    self.label_7.setText("The CenterBack position requires"+"\n-Tackling"+"\n-Strength")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/rv1.jpg"))
                elif k == "Goalkeeper":
                    self.label_7.setText("The Goalkeeper position requires"+"\n-Handling"+"\n-Positioning")
                    self.label_8.setPixmap(QtGui.QPixmap("C:/Users/ACER/Dropbox/My PC (LAPTOP-GTQ01APL)/Desktop/งานมหาลัย/pictures for project oython/gk.jpg"))

            
 

##        print(cal)
        
            
            
        

        
        


   

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "NEXT"))
        self.pushButton_2.setText(_translate("MainWindow", "NEXT"))
        self.pushButton_4.setText(_translate("MainWindow", "SAVE"))
        self.comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_2.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_2.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_2.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_2.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_3.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_3.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_3.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_3.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_4.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_4.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_5.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_5.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_5.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_5.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_5.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_5.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_6.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_6.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_6.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_6.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_6.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_7.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_7.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_7.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_7.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_7.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_8.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_8.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_8.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_8.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_8.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_8.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_10.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_10.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_10.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_10.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_10.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_10.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_11.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_11.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_11.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_11.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_11.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_11.setItemText(9, _translate("MainWindow", "10"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "1"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "2"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "3"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "4"))
        self.comboBox_12.setItemText(4, _translate("MainWindow", "5"))
        self.comboBox_12.setItemText(5, _translate("MainWindow", "6"))
        self.comboBox_12.setItemText(6, _translate("MainWindow", "7"))
        self.comboBox_12.setItemText(7, _translate("MainWindow", "8"))
        self.comboBox_12.setItemText(8, _translate("MainWindow", "9"))
        self.comboBox_12.setItemText(9, _translate("MainWindow", "10"))
        self.pushButton_3.setText(_translate("MainWindow", "NEXT"))
        self.pushButton_5.setText(_translate("MainWindow", "ANALYZE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


